### ISSUE TITLE
no "waiting for browser to connect" message

### ISSUE THREAD

**Issue by rlargett** [mockko/livereload#103]
I'm working on windows xp and I get this output when I try to run livereload on a directory. Any ideas what's going on?

~/website/mfctoday$ livereload
c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher.rb:7: Use RbConfig instead
of obsolete and deprecated Config.

Version:  1.6  (compatible with browser extension versions 1.6.x)
Port:     35729
Watching: u:/website/mfctoday
- extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb
- live refreshing disabled for .js: will reload the whole page when .js is changed
- excluding changes in: _/.git/_ _/.svn/_ _/.hg/_
- with a grace period of 0.05 sec after each change
  c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/windows.rb:88:in `popen': No such file or directory - "ruby" "c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/windows/monitor.rb" 2019 "u:/website/mfctoday" (Errno::ENOENT)
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/windows.rb:88:in`setup_listener'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/windows.rb:34:in `initialize'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in`new'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in `watch'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/lib/livereload.rb:180:in`restart_watching'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/lib/livereload.rb:249:in `block (2 levels) in run'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/lib/livereload.rb:249:in`each'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/lib/livereload.rb:249:in `block in run'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86-mingw32/lib/eventmachine.rb:179:in`call'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86-mingw32/lib/eventmachine.rb:179:in `run_machine'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86-mingw32/lib/eventmachine.rb:179:in`run'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/lib/livereload.rb:220:in `run'
      from c:/Ruby193/lib/ruby/gems/1.9.1/gems/livereload-1.6.1/bin/livereload:51:in`<top (required)>'
      from c:/Ruby193/bin/livereload:19:in `load'
      from c:/Ruby193/bin/livereload:19:in`<main>'

**Comment by imarco** [comment]
I have the same problem.

**Comment by rlargett** [comment]
I found a solution.

I just started using [Sublime Text 2](http://http://www.sublimetext.com/2) editor and it has a LiveReload package addon that works with the LiveReload addons for Chrome and Firefox. So far it works great and you don't need the Ruby Gems installed.

**Comment by milworm** [comment]
Same problem for me
