### ISSUE TITLE
Undefined method 'reduce'

### ISSUE THREAD

**Issue by melo** [mockko/livereload#16]
Hi,

OS: Mac OS X 10.5.8
uname: Darwin DogsHouse.local 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
livereload --version: 1.3

When I start livereload, the following is printed:

```
/Users/melo/.gem/ruby/1.8/gems/livereload-1.3/lib/livereload.rb:95:in `merge': undefined method `reduce' for #<Array:0x11b2e9c> (NoMethodError)
    from /Users/melo/.gem/ruby/1.8/gems/livereload-1.3/lib/livereload.rb:200:in `run'
    from /Users/melo/.gem/ruby/1.8/gems/livereload-1.3/bin/livereload:51
    from /Users/melo/.gem/ruby/1.8/bin/livereload:19:in `load'
    from /Users/melo/.gem/ruby/1.8/bin/livereload:19
```

Any ideas? Not a ruby user...

Thanks

**Comment by melo** [comment]
Just saw Issue 13, this one is a duplicate.
