### ISSUE TITLE
Windows version requires win32-event gem

### ISSUE THREAD

**Issue by charlesroper** [mockko/livereload#19]
It looks like the win32-event gem is required, but this isn't mentioned in the installation docs. Once I did `gem install win32-event` it worked like a charm.    

```
[C:\Users\charlesr\My Dropbox\Projects\SARG\Prototype]livereload

Version:  1.4  (compatible with browser extension versions 1.4.x)
Port:     35729
Watching: C:/Users/charlesr/My Dropbox/Projects/SARG/Prototype
  - extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb .haml .sass
  - excluding changes in: */.git/* */.svn/* */.hg/*
  - with a grace period of 0.05 sec after each change

LiveReload is waiting for browser to connect.
C:/Users/charlesr/Tools/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- win32/event (LoadError)
        from C:/Users/charlesr/Tools/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from C:/Users/charlesr/Tools/Ruby187/lib/ruby/gems/1.8/gems/win32-changenotify-0.5.1/lib/win32/changenotify.rb:1
        from C:/Users/charlesr/Tools/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
        from C:/Users/charlesr/Tools/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from C:/Users/charlesr/Tools/Ruby187/lib/ruby/gems/1.8/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/windows/monitor.rb:4
```

**Comment by andreyvit** [comment]
Right, our bad.

**Comment by dottedmag** [comment]
Fixed in installation instructions.
