### ISSUE TITLE
Is livereload incompatible with ruby 1.9.2?

### ISSUE THREAD

**Issue by lmartins** [mockko/livereload#63]
I get the following when running livereload with ruby 1.9.2

Luis-Martinss-Mac-Pro:wip005 luismartins$ livereload

Version:  1.6  (compatible with browser extension versions 1.6.x)
Port:     35729
Watching: /Users/luismartins/Sites/wip005
- extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb .tpl
- excluding changes in: (?-mix:(images|tmp)) _/.git/_ _/.svn/_ _/.hg/_
- with a grace period of 0.05 sec after each change

LiveReload is waiting for browser to connect.
/Users/luismartins/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- osx/foundation (LoadError)
    from /Users/luismartins/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac/rubycocoa_watcher.rb:2:in `<top (required)>'
    from /Users/luismartins/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/luismartins/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:16:in`block in initialize'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in `call'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in`start_subprocess'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:20:in `initialize'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in`new'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in `initialize'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in`new'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in `watch'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/lib/livereload.rb:180:in`restart_watching'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/lib/livereload.rb:249:in `block (2 levels) in run'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/lib/livereload.rb:249:in`each'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/lib/livereload.rb:249:in `block in run'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/lib/livereload.rb:220:in `run'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/gems/livereload-1.6/bin/livereload:51:in`<top (required)>'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/bin/livereload:19:in `load'
    from /Users/luismartins/.rvm/gems/ruby-1.9.2-p180/bin/livereload:19:in`<main>'

**Comment by NV** [comment]
Ruby can't find RubyCocoa.

I've tried to install RubyCocoa on rvm using https://gist.github.com/294465. It fails:

<pre>~/RubyCocoa-1.0.0$ ruby install.rb config --build-universal=yes
install.rb: entering config phase...
create ext/rubycocoa/extconf.rb
create framework/GeneratedConfig.xcconfig
create framework/src/objc/Version.h
create tests/Makefile
---> framework
create /Users/nv/Downloads/RubyCocoa-1.0.0/framework/src/objc/osx_ruby.h ...
config failed
hook /Users/nv/Downloads/RubyCocoa-1.0.0/framework/post-config.rb failed:
No such file or directory - /Users/nv/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/x86_64-darwin10.6.0/ruby.h
try 'ruby install.rb --help' for usage</pre>


Is there anyone who successfully installed RubyCocoa on rvm with 1.9.2?

**Comment by lmartins** [comment]
Im reading loads of stuff about this kind of errors but no success so far.

**Comment by mattfordham** [comment]
I am having the same problem using RVM and Ruby 1.9.2. Wondering if there is any official word on this. Has anyone had success w/ RVM and 1.9.2?

**Comment by fwoeck** [comment]
you can do a trick: the system ruby comes with cocoa enabled, so you can

a) install and start the livereload gem there:
rvm use system; gem install livereload

or b) do a blend in that you install the gem in your rvm gemset (if any) and call livereload with the explizit system binary like:

/usr/bin/ruby `which livereload`

Personally, I use the guard-livereload gem with success.

(please allow for minor changes, I typed this from memory)
--Frank

**Comment by bitboxer** [comment]
This is basically a duplicate of #26 ... this problem is long known but it looks like nobody on the core team cares about ruby 1.9.2 :( .

**Comment by nofxx** [comment]
Should be renamed to "Is compatible with OSX" , it works flawlessly on archlinux/ruby 1.9.2.
Thanks for this, sad I didn't find this gem earlier.

**Comment by bitboxer** [comment]
No, it should be closed and marked as duplicate of #26 :)
