### ISSUE TITLE
registering with kqueue: Too many open files

### ISSUE THREAD

**Issue by millisami** [mockko/livereload#9]
The version is 1.3 and it blows up with the Too many open files error.
        ree-1.8.7-2010.02@automation [~/rails_apps/automation (refactor)⚡] ➔ livereload

```
    Version:  1.3  (compatible with browser extension versions 1.3.x)
    Port:     10083
    Watching: /Users/millisami/rails_apps/automation
      - extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb .haml
      - excluding changes in: /public/javascripts/* */.git/* */.svn/* */.hg/*
    /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:1266:in `watch_filename': Too many open files - failed to open file /Users/millisami/rails_apps/automation/public/javascripts/right/i18n/ru.js for registering with kqueue: Too many open files (Errno::EMFILE)
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:1266:in `watch_file'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/directory_watcher-1.3.2/lib/directory_watcher/em_scanner.rb:187:in `_watch_file'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/directory_watcher-1.3.2/lib/directory_watcher/em_scanner.rb:69:in `start'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/directory_watcher-1.3.2/lib/directory_watcher/em_scanner.rb:67:in `each'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/directory_watcher-1.3.2/lib/directory_watcher/em_scanner.rb:67:in `start'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/directory_watcher-1.3.2/lib/directory_watcher.rb:497:in `start'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/lib/livereload.rb:185:in `restart_watching'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/lib/livereload.rb:237:in `run'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/lib/livereload.rb:237:in `each'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/lib/livereload.rb:237:in `run'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@global/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/lib/livereload.rb:209:in `run'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/gems/livereload-1.3/bin/livereload:51
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/bin/livereload:19:in `load'
            from /Users/millisami/.rvm/gems/ree-1.8.7-2010.02@automation/bin/livereload:19
    ree-1.8.7-2010.02@automation [~/rails_apps/automation (refactor)⚡] ➔ 
```

**Comment by andreyvit** [comment]
Please see http://github.com/mockko/livereload/issues#issue/1 (there's a workaround there) — closing this as a duplicate.
